version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=marcote
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=BDCurso
    volumes:
        - pgdata:/data/postgres


  redis:
    image: redis:alpine
    restart: always
    ports:
        - 6379:6379
    volumes: 
        - cache:/data        
  app:
    build: .
    container_name: Curso-node
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      
      
    links:
        - database_ignite
        - redis
    depends_on:
        - database_ignite  
        - redis    
    

volumes:
    pgdata:  
        driver: local    
    cache:
        driver: local