version: "3.7"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
        - 6379:6379
    volumes: 
        - cache:/data        
  app:
    build: .
    container_name: Curso-node
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
      
      
    links:
        - redis
    depends_on:
        - redis    
    

volumes:
    pgdata:  
        driver: local    
    cache:
        driver: local